### ISSUE TITLE
Specify Job class for Scheduler

### ISSUE THREAD

**Issue by antoine-lizee** [rq/rq-scheduler#147]
Since the `Scheduler()` object is also responsible for creating the job (unless I missed something), it would be desirable to have it accept a `job_class` and behave like the `Queue` objects.

Another solution would be to specify a queue object when scheduling a job (and at object instantiation as default) so it can 'inherit' attributes and behavior from the queue directly: not only the `queue_name` but also the `job_class` and even the job creation method maybe ? 
What is the thinking behind this versus duplicating all the job creation logic from the `Queue` objects into the `Scheduler` ?

**Comment by selwin** [comment]
When rq-scheduler was first started, RQ didn't have job_class and queue_class parameters yet. I'm open to proposals on how best to change the way we instantiate the Scheduler so we can accommodate other use cases.

Please also take a look at https://github.com/ui/rq-scheduler/pull/148 which is somewhat related.

**Comment by antoine-lizee** [comment]
How ironic that both this issue and the proposed PR have been written the same day :-)

The proposed change from @flacerdk enables choosing the queue, and as a result solves my problem. Thanks!
