### ISSUE TITLE
Is it possible to get job I'd after creating a job?

### ISSUE THREAD

**Issue by brandon-binary** [rq/rq-scheduler#178]
I want to have multiple users schedule jobs but I can't have them interfere with each other's jobs so could you get job IDs after creating a job? This is so users can cancel jobs and re add them again

**Comment by YiiKuoChong** [comment]
By reading the code, it seems that enqueue_at returns a job object

**Comment by Segerberg** [comment]
can’t you use a custom id for the job?

**Comment by selwin** [comment]
Yes, a job object is returned when `scheduler.schedule()` is called.
