### ISSUE TITLE
Conflicting argument for -q in scripts/rqscheduler.py

### ISSUE THREAD

**Issue by sourcepirate** [rq/rq-scheduler#179]
The same -q argument is conflicting between --quite and --queue-class. Which causes problem when running the rqscheduler cli.

**Comment by sourcepirate** [comment]
I would be happy to raise a PR when you decide on what should be the option name for either --quite or --queue-class.
Thanks.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq-scheduler/pull/180
