### ISSUE TITLE
Latest changes in master missing

### ISSUE THREAD

**Issue by jezdez** [rq/rq-scheduler#182]
@selwin When looking at https://github.com/rq/rq-scheduler/compare/v0.7.0...v0.8.1 I see there were changes, but they are not in master. Did you push both the master as well as the tags?

**Comment by jezdez** [comment]
Also the v0.8.2 tag is missing.

**Comment by selwin** [comment]
Sorry, I forgot to push my local git repo the Github. It's a bad habit :(. It's fixed now.
