### ISSUE TITLE
Documentation needs update. queue vs queue_name

### ISSUE THREAD

**Issue by jgerry2002** [rq/rq-scheduler#186]
In the example:

scheduler = Scheduler(queue=queue) 

This will return errors regarding connectivity to redis, when in fact it the option argument is now queue_name vs queue.

When I tested:

scheduler = Scheduler(queue_name=queue)

Everything worked as it should.

**Comment by sikula** [comment]
@jgerry2002 I tried this and wasn't able to get it to work.  When I try to run it with a normal queue, it works perfectly fine and I can add jobs to the queue, but with the scheduler, I get an error.  This is my code:

```
from redis import Redis
from rq import Queue
from rq_scheduler import Scheduler

rq = Queue(connection=Redis(host=BaseConfig.REDIS_HOST, port=BaseConfig.REDIS_PORT))
rqs = Scheduler(queue_name=rq)
```

And I'm still getting a `NoRedisConnectionException: Could not resolve a Redis connection` error.

**Comment by mindset-team** [comment]
@sikula , add the connection parameter to Scheduler:
```python
redis_conn = Redis(host=BaseConfig.REDIS_HOST, port=BaseConfig.REDIS_PORT)
rq = Queue(connection=redis_conn)
rqs = Scheduler(queue_name=rq, connection=redis_conn)
```
you can see show Scheduler is constructed [here](https://github.com/rq/rq-scheduler/blob/baa0d37e925b9da5e8525744206efc68fa0a4258/rq_scheduler/scheduler.py#L26)

**Comment by selwin** [comment]
Added an additional example in this commit that will hopefully clarify things a bit more: https://github.com/rq/rq-scheduler/commit/ee60c19e42a46ba787f762733a0036aa0cf2f7b7
