### ISSUE TITLE
ValueError: There's already an active RQ scheduler

### ISSUE THREAD

**Issue by paulocheque** [rq/rq-scheduler#19]
I am receiving this error, but I can not find the process running. Any ideas?

**Comment by nicolaevladescu** [comment]
Hi.

If this is fixed in 0.7.0 why am i still getting this:
```
File "/usr/local/lib/python3.5/site-packages/rq_scheduler/scheduler.py", line 33, in register_birth
    raise ValueError("There's already an active RQ scheduler")
```
Also, despite the error, i can still see the process running, but is it running ok? Should i restart it? Has it restarted itself?

How should i handle this exception outside python ?

Thanks.

**Comment by Fajkowsky** [comment]
This error still occurs.

**Comment by megapctr** [comment]
My app is running in docker-compose. When I need to deploy a new version, the scheduler often needs to be restarted, and sometimes this results in the error discussed here.

I had the same problem with workers actually, but I made a small change in how workers are spawned:
```
 ./manage.py rqworker --name $RANDOM
```
(this is a command from django-rq which effectively calls `rq.Worker(name=$RANDOM)`)

I see that it's not possible to spawn a scheduler with a custom name. However, I could supply my own Scheduler class, and set a different `scheduler_key` property for each deployment.

Would this be the recommended approach?

**Comment by peterlada** [comment]
@megapctr Filip, did your approach work? It might pollute the redis keystore with "birth" registrations, no?

**Comment by megapctr** [comment]
To be honest, it happens so rarely I didn't get to implement it yet 🙂 But the old scheduler names should get removed pretty quickly

**Comment by zachliu** [comment]
@megapctr have you tried v0.10.0? which allows multiple schedulers running at the same time, but only one scheduler will be active
