### ISSUE TITLE
What happens when workers are not running?

### ISSUE THREAD

**Issue by variable** [rq/rq-scheduler#193]
Say I have scheduler with cron jobs and the queue workers died, would it keep enqueuing jobs so the next time the worker starts will pick up all the jobs?

**Comment by mindset-team** [comment]
deliberately kill the workers, wait for some jobs to accumulate and restart the workers - this should give you an answer.

**Comment by as3445** [comment]
Yes, the scheduler will still enqueue the jobs into a sorted set (which is a score value pair where the score is the time when it needs to be executed) in Redis, and will move the task into a set (RQ uses this to implement the queue) when it is ready to be executed even if the worker is dead. The tasks will accumulate in Redis if the worker is dead, but will be picked up by the worker when it's up again.

**Comment by variable** [comment]
@as3445 Thanks for the answer, I would have expected the behavior will be the same as Linux cronjob if it couldn't execute the job will just forget it.
