### ISSUE TITLE
rq 1.0 support?

### ISSUE THREAD

**Issue by lucasnad27** [rq/rq-scheduler#206]
Has rq-scheduler been tested against [RQ 1.0 release](https://github.com/rq/rq/blob/master/CHANGES.md#10-2019-04-06)? I know there are some breaking changes. I found [this commit](https://github.com/rq/rq-scheduler/commit/a477251f65357cdc9ed4cd48e0449b1ed9465604) that implies >=0.13 is supported, but I assume this was not done with 1.0.

Thank you for any information and let me know if you would like help with this patch and I will try to find time :)

**Comment by selwin** [comment]
Yes, this library should be compatible with RQ v1.0 :)
