### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by woodruffw** [rq/rq-scheduler#209]
First of all, thanks for both `rq` and `rq-scheduler`!

Would it be possible to get a new release cut and published here? The current latest version on PyPI includes usage of `_zadd` that no longer work with `redis>3.0`, despite `rq` transitively requiring `redis>3.0`. It looks like these commits on `master` make the relevant fixes:

* a477251f65357cdc9ed4cd48e0449b1ed9465604
* 1822f7a17230a437ed6001dda3d3ce824b622f48

Thanks again!

**Comment by mawaldne** [comment]
I would also love a new release :)

**Comment by dmwyatt** [comment]
What do you think @selwin ?

**Comment by selwin** [comment]
Will try make a new release this weekend.

**Comment by selwin** [comment]
Version 0.9.1 is now up on PyPI https://pypi.org/project/rq-scheduler/
