### ISSUE TITLE
How to reschedule jobs that failed?

### ISSUE THREAD

**Issue by taewookim** [rq/rq-scheduler#234]
Im looking for a way to requeue a job that failed w/ max # of retries & exponential back off (i.e. schedule job in future).

I saw [this post](https://github.com/rq/rq/issues/1067) , so I thought i could use a scheduler to re-queue job (and add num_retry in meta). 

Any other elegant solutions?

**Comment by selwin** [comment]
I'm working on a PR that adds job retry feature natively into RQ here https://github.com/rq/rq/pull/1299 . It's not yet released, but should be done sometime in the next few weeks.
