### ISSUE TITLE
Jobs dispatched EARLIER than scheduled

### ISSUE THREAD

**Issue by taewookim** [rq/rq-scheduler#246]
I'm seeing that jobs in scheduler get executed EARLIER than as defined in "enqueue_at".

I thought it was issue with UTC datetime, but that doesnt' seem to be the issue.

Not sure if this matters but I have multiple schedulers and multiple workers... (as recommended in the docs).  

According to [this doc](https://python-rq.org/docs/scheduling/):

> Note that if you pass in a naive datetime object, RQ will automatically convert it to the local timezone.

However, comment in this repo says 

> scheduler.enqueue_at(datetime(2020, 1, 1), func) # Date time should be in UTC

Bit confused which im supposed to pass

Any ideas?

**Comment by taewookim** [comment]
Example:

=================================
At, 2020-08-25 21:51:00+00:00, I add 1 job to queue
=================================
[job 1] send_date: 2020-08-25 21:55:00+00:00

=================================
At 2020-08-25 21:52:00+00:00, two things happen
=================================
1) I add 2 more jobs added

[job 1] send_date: 2020-08-25 21:55:00+00:00
[job 2] send_date: 2020-08-25 22:00:00+00:00
[job 3] send_date: 2020-08-25 22:05:00+00:00

2) Job 1 is launched

=================================
At 2020-08-25 21:53:00+00:00
=================================

Job2 and job 3 are both launched



IN all cases, the jobs are launched AHEAD of their scheduled time

**Comment by taewookim** [comment]
[SO](https://stackoverflow.com/questions/63588159/python-rq-jobs-dispatched-earlier-than-scheduled) post

**Comment by taewookim** [comment]
This was happening b/c i was passing naive datetime but RQ scheduler was expecting timezone aware datetime.

**Comment by petervtzand** [comment]
👍  It was probably better to raise an error when passing a non timezone aware datetime.
