### ISSUE TITLE
Possible to run more than one rq-scheduler?

### ISSUE THREAD

**Issue by daf** [rq/rq-scheduler#40]
Hi, I'm trying to adjust my application to use two queues (priority based) - they currently all just sit in `default`.  I have a custom runner for rq-scheduler, similar to:

``` python
#!/usr/bin/env python

from rq_scheduler import Scheduler
scheduler = Scheduler('default', connection=redis_connection)
scheduler.run()
```

I tried to add a second similar python script, specifying a different queue, but I get this:

```
ValueError: There's already an active RQ scheduler
```

Looking at code this confirms it registers itself at a single key in the Redis db.  The `rqscheduler` executable script provided on rq-scheduler installation doesn't even take a queue name - it's just `default`, so I can't run two of those either.

Is it even possible to do what I want to do here?

**Comment by nhumrich** [comment]
Id like to reopen for a different use-case. I care about HA, so I would prefer there be at least two workers running just in case one crashes. So same question, is it even possible to run two at the same time?
